// -*- C++ -*- generated by wxGlade 0.4.1 on Mon Jul 31 13:34:58 2006

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/fileconf.h>
#include <wx/stdpaths.h>
#include <wx/wfstream.h>
#include <stdio.h>

#ifndef FILEDETAILS_H
#define FILEDETAILS_H

#include "avelib.h"
#include "tfile.h"
#include "TCalibrate.h"

#ifdef __WIN32__
#define snprintf _snprintf
#endif

// begin wxGlade: ::dependencies
// end wxGlade

#define CAL_BUTTON (wxID_HIGHEST + 1)


class FileDetails: public wxFrame {
public:
    // begin wxGlade: FileDetails::ids
    // end wxGlade

    FileDetails(const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize);

private:
    // begin wxGlade: FileDetails::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    int lOpenCount;
    TAvInfo  lOpenFile;
    PFileArray FFiles;     //In Delphi version is list of files

    bool Calculate(WData ** CoData, bool UFoil);
    bool ReadGDF (wxString Filename);
    void OpenFileDone();  //In Delphi is openfilethreaddone
    void AddFile();       //Create new, empty file entry

// Following were thread-local values

    wxString FFileName;
    TFile *     FFile;
    TAvFileInfo lD;
    double lE0;

protected:
    // begin wxGlade: FileDetails::attributes
    wxButton* LoadButton;
    wxButton* CalibrateButton;
    wxButton* SaveButton;
    wxPanel* FilePanel;
    wxButton* CloseButton;
    wxBoxSizer * file_sizer;   //for each row of lights
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void LoadButtonClick(wxCommandEvent &event); // wxGlade: <event_handler>
    void CalButtonClick(wxCommandEvent &event); // wxGlade: <event_handler>
    void SaveButtonClick(wxCommandEvent &event); // wxGlade: <event_handler>
    void CloseButtonClick(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // FILEDETAILS_H
